name: isar_benchmark

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  isar: ^3.0.2
  isar_flutter_libs: any

  objectbox: ^1.6.2
  objectbox_flutter_libs: any

  realm: ^0.6.0+beta

  path_provider: ^2.0.10
  english_words: ^4.0.0
  fl_chart: ^0.55.0
  share_plus: ^4.0.4
  device_info_plus: ^4.0.0
  drift: ^2.0.2
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.2
  analyzer: ^4.0.0
  ffi: ^2.0.1
  dartx: ^1.1.0
  flex_color_scheme: ^6.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  isar_generator: ^3.0.2
  objectbox_generator: any
  drift_dev: ^2.0.2

flutter:
  uses-material-design: true
