name: isar_benchmark

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  isar: ^3.0.0-dev.10
  isar_flutter_libs: any

  objectbox: ^1.5.0
  objectbox_flutter_libs: any

  realm: ^0.3.1+alpha

  path_provider: ^2.0.10
  english_words: ^4.0.0
  fl_chart: ^0.55.0
  share_plus: ^4.0.4
  device_info_plus: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: any
  isar_generator: ^3.0.0-dev.10
  objectbox_generator: any

dependency_overrides:
  analyzer: ^4.1.0
  ffi: ^2.0.0

flutter:
  uses-material-design: true
